# Site settings
title: Zachary I. Schutzman
email: ianzach (at) seas (dot) upenn (dot) edu
description: > # this means to ignore newlines until "baseurl:"
 I do math and computers
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://zachdoesmath.com" # the base hostname & protocol for your site
twitter_username: zschutzy
github_username:  zschutzman
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
